# Capturer - 视频抓拍服务
# A Rust-based video capturing service that captures images from video streams
[workspace]
members = ["capturer-svr"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.104"
arc-swap = "1.9.2"
ctor = "1.0.13"
tracing = "0.1.44"
thiserror = "2.0.20"
clap = "4.6.6"
chrono = "0.4.45"
serde = "1.0.229"
serde_with = "3.22.0"
serde_json = "1.0.151"
tokio = "1.53.1"
tokio-stream = "0.1.19"
validator = "0.21.0"
axum = "0.8.9"
utoipa = "5.5.0"
utoipa-swagger-ui = "9.0.2"
image = "0.25.10"
rustc-hash = "2.1.3"
bytes = "1.12.1"
futures = "0.3.34"
async-stream = "0.3.6"
linkme = "0.3.37"


# cross打包时用，需要开启vendored feature
openssl = { version = "0.10.81" }

wheel-rs = "1.9.4"
robotech = "1.10.0"
oss-api-client = "1.1.7"


[patch.crates-io]
wheel-rs = { path = "../wheel-rs" }
robotech = { path = "../robotech-rs/robotech" }
robotech-macros = { path = "../robotech-rs/robotech-macros" }
oss-api-client = { path = "../oss-rs/oss-api-client" }
